version: '3.8'

services:
  # Database
  postgres:
    image: postgres:13
    container_name: ecommerce_db
    env_file:
      - ./config/db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  # User Service
  user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8000:8000"
    env_file:
      - ./config/db.env
      - ./config/user-service.env
    depends_on:
      - postgres
    networks:
      - ecommerce_network

  # Product Service
  product_service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product_service
    ports:
      - "8001:8001"
    env_file:
      - ./config/db.env
      - ./config/product-service.env
    depends_on:
      - postgres
      - user_service
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
    driver: bridge